const BANNER_BACKGROUND_DIRECTORY = "assets/BOLA/banner_background";
const BASKETBALL_BRAND_BACKGROUND_DIRECTORY = "assets/BASKET/banner_background";
const ESPORT_BRAND_BACKGROUND_DIRECTORY = "assets/ESPORT/banner_background";

export {
  BANNER_BACKGROUND_DIRECTORY,
  BASKETBALL_BRAND_BACKGROUND_DIRECTORY,
  ESPORT_BRAND_BACKGROUND_DIRECTORY,
};

